#!/bin/sh
set -efu

export PYTHONWARNINGS=d
# Use patched hypercorn; see https://github.com/urllib3/urllib3/issues/3334
export PYTHONPATH=$(pwd)/debian/vendor
# Use longer timeouts, see https://github.com/urllib3/urllib3/issues/3164
export CI=1

python3_all="$(py3versions -s 2>/dev/null)"

cp -r dummyserver test "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"

for py in $python3_all; do
    echo "=== $py ==="
    $py -m pytest --verbose -k "not requires_network and not test_recent_date"
done
