#!/bin/sh
set -efu

export PYTHONWARNINGS=d

python3_all="$(py3versions -s 2>/dev/null)"

cp -r test "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
rm -f test/conftest.py

for py in $python3_all; do
    echo "=== $py ==="
    $py -m pytest --verbose --ignore=test/appengine \
    --ignore=test/contrib/test_pyopenssl.py \
    --ignore=test/contrib/test_securetransport.py \
    --ignore=test/contrib/test_socks.py \
    --ignore=test/test_connectionpool.py \
    --ignore=test/test_ssl.py \
    --ignore=test/test_ssltransport.py \
    --ignore=test/with_dummyserver \
    -k 'not test_recent_date and not test_respect_retry_after_header_sleep' 2>&1

done
